# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29893ffe4d4c0be05cb0c42c7fc77ab27994c7eb9b8d34406e86742e383b3d4f5ddce5af79058777d8499f4ad1213cccb449351e7f7b005e9514bd53252b929e

test:
  secret_key_base: 8c626b36fbffa9d06a26c5e91ad45ee1270adcddb59940bcd1395808b144386bfd5d1b2fddec6b5eec2714aaef93fa49f33805d90cff961133cf677c1115fac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
